### ISSUE TITLE
SyntaxError: invalid syntax "<<<<<<< Updated upstream"

### ISSUE THREAD

**Issue by gvt** [baali/zulip-docker#2]
After I have built the docker image, trying to run the container fails with an error:

```
$ sudo docker run --name zulip -i -t -p 9991:9991 tulip-instance
Warning: PID file not written; -detached was passed.
Starting memcached: memcached.
 * Starting PostgreSQL 9.3 database server         [ OK ]
--2016-02-26 09:42:01--  https://raw.githubusercontent.com/zulip/zulip/master/puppet/zulip/files/postgresql/zulip_english.stop
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.47.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.47.133|:443... connected.
HTTP request sent, awaiting response... 200 OK

..... <a lot of output omitted> ....

Database created
Operations to perform:
  Synchronize unmigrated apps: staticfiles, analytics, pipeline
  Apply all migrations: zilencer, confirmation, sessions, guardian, zerver, sites, auth, contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying confirmation.0001_initial... OK
  Applying zerver.0001_initial... OK
  Applying guardian.0001_initial... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying zerver.0002_django_1_8... OK
  Applying zerver.0003_custom_indexes... OK
  Applying zerver.0004_userprofile_left_side_userlist... OK
  Applying zerver.0005_auto_20150920_1340... OK
  Applying zilencer.0001_initial... OK
[clean-repo] Deleting ./analytics/__init__.pyc
[clean-repo] Deleting ./analytics/management/__init__.pyc
[clean-repo] Deleting ./zerver/lib/utils.pyc
[clean-repo] Deleting ./zerver/lib/queue.pyc
[clean-repo] Deleting ./zerver/lib/logging_util.pyc
[clean-repo] Deleting ./zerver/lib/avatar.pyc
[clean-repo] Deleting ./zerver/lib/cache.pyc
[clean-repo] Deleting ./zerver/lib/__init__.pyc
[clean-repo] Deleting ./zerver/lib/db.pyc
[clean-repo] Deleting ./zerver/lib/timestamp.pyc
[clean-repo] Deleting ./zerver/migrations/0005_auto_20150920_1340.pyc
[clean-repo] Deleting ./zerver/migrations/0003_custom_indexes.pyc
[clean-repo] Deleting ./zerver/migrations/0001_initial.pyc
[clean-repo] Deleting ./zerver/migrations/0002_django_1_8.pyc
[clean-repo] Deleting ./zerver/migrations/__init__.pyc
[clean-repo] Deleting ./zerver/migrations/0004_userprofile_left_side_userlist.pyc
[clean-repo] Deleting ./zerver/__init__.pyc
[clean-repo] Deleting ./zerver/models.pyc
[clean-repo] Deleting ./zerver/management/__init__.pyc
[clean-repo] Deleting ./zerver/handlers.pyc
[clean-repo] Deleting ./confirmation/migrations/0001_initial.pyc
[clean-repo] Deleting ./confirmation/migrations/__init__.pyc
[clean-repo] Deleting ./confirmation/__init__.pyc
[clean-repo] Deleting ./confirmation/models.pyc
[clean-repo] Deleting ./confirmation/management/__init__.pyc
[clean-repo] Deleting ./confirmation/util.pyc
[clean-repo] Deleting ./zproject/settings.pyc
[clean-repo] Deleting ./zproject/__init__.pyc
[clean-repo] Deleting ./zproject/local_settings_template.pyc
[clean-repo] Deleting ./zilencer/migrations/0001_initial.pyc
[clean-repo] Deleting ./zilencer/migrations/__init__.pyc
[clean-repo] Deleting ./zilencer/__init__.pyc
[clean-repo] Deleting ./zilencer/models.pyc
[clean-repo] Deleting ./zilencer/management/__init__.pyc
  File "./puppet/zulip/files/postgresql/process_fts_updates", line 30
    <<<<<<< Updated upstream
     ^
SyntaxError: invalid syntax
Recompiling templates
done
Validating Django models.py...
System check identified no issues (0 silenced).

Django version 1.8
Tornado server is running at http://localhost:9993/
Quit the server with CTRL-C.
2016-02-26 04:42:16,360 INFO     Beginning TornadoQueueClient connection
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/srv/zulip/zerver/management/commands/runtornado.py", line 119, in handle
    inner_run()
  File "/srv/zulip/zerver/management/commands/runtornado.py", line 84, in inner_run
    queue_client = get_queue_client()
  File "/srv/zulip/zerver/lib/queue.py", line 238, in get_queue_client
    queue_client = TornadoQueueClient()
  File "/srv/zulip/zerver/lib/queue.py", line 158, in __init__
    super(TornadoQueueClient, self).__init__()
  File "/srv/zulip/zerver/lib/queue.py", line 25, in __init__
    self._connect()
  File "/srv/zulip/zerver/lib/queue.py", line 168, in _connect
    stop_ioloop_on_close = False)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/pika/adapters/tornado_connection.py", line 55, in __init__
    stop_ioloop_on_close)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 72, in __init__
    on_close_callback)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/pika/connection.py", line 600, in __init__
    self.connect()
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/pika/connection.py", line 718, in connect
    self.callbacks.process(0, self.ON_CONNECTION_ERROR, self, self, error)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/pika/callback.py", line 61, in wrapper
    return function(*tuple(args), **kwargs)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/pika/callback.py", line 232, in process
    callback(*args, **keywords)
  File "/srv/zulip-venv/local/lib/python2.7/site-packages/pika/connection.py", line 1206, in _on_connection_error
    self.params.connection_attempts)
pika.exceptions.AMQPConnectionError: Connection to 127.0.0.1:5672 failed: [Errno 111] Connection refused
Performing system checks...

..... <more output of more errors like the one above> ....

```

It seems like a merge conflict that was committed to the code and is causing a syntax error. I looked through this repo and the zulip/zulip repo and haven't found the code that actually contains `<<<<<<< Updated upstream`.

**Comment by baali** [comment]
Hello @gvt 
In the [shell script](https://github.com/baali/zulip-docker/blob/master/zulip_docker.sh) which gets called while "running" the instance I try to checkout a particular revision of zulip:
git checkout ae04744
git stash pop

I think the process_fts_updates which I "add" is having merge issues with main repo and when I pop the changes those conflicts are showing up and causing the trouble. I think you will have to find a better way to handle this step.
